<a href="https://colab.research.google.com/github/jnprogrammer/MachineLearning/blob/master/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install -q tensorflow-gpu==2.0.0-beta1
import tensorflow as tf
print(tf.__version__)

2.0.0-beta1


In [0]:
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
# Things you should automatically know and have memorized
# N = number of samples
# T = sequence length
# D = number of input features
# M = number of hidden units
# K = numbers of output units

In [0]:
# Make some data
N = 34
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [0]:
#making the RNN

M = 5
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i,x) 

In [19]:
Yhat = model.predict(X)
print(Yhat)

[[-0.2823568   0.88105714]
 [-0.20467706  0.17937033]
 [-0.09602202 -0.9275055 ]
 [-0.20606059 -0.40168217]
 [ 0.4003079  -1.1276546 ]
 [-0.01510127 -0.5831378 ]
 [-0.28864577  0.01005843]
 [-0.14373633  0.90085816]
 [-0.01960107 -0.4316502 ]
 [-0.49713245  0.09966299]
 [-0.16686511  0.90671647]
 [ 0.05030283 -0.56424063]
 [ 0.21161935  0.2422695 ]
 [-0.14329028  0.72745377]
 [-0.10607946 -1.2011887 ]
 [ 0.05521714 -0.8862661 ]
 [-0.3474716  -0.6443435 ]
 [ 0.5331424  -1.0253695 ]
 [-0.07815638 -1.2164677 ]
 [-0.25691175  0.86713624]
 [ 0.29187453  0.92236775]
 [-0.12405653 -0.70485705]
 [ 0.03705642 -0.91759694]
 [ 0.23150478  1.1172045 ]
 [-0.15216291 -0.46919197]
 [-0.40230253  1.2056044 ]
 [ 0.4983215   0.01343695]
 [-0.16326769  0.57290524]
 [ 0.02059999  0.28949946]
 [-0.03345911 -0.11673969]
 [ 0.09206696 -0.8269212 ]
 [ 0.17160723 -1.5701953 ]
 [ 0.0073523   0.12996048]
 [-0.3008979   0.38614437]]


In [20]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.layers[1].get_weights()

[array([[-0.7246701 ,  0.28572184,  0.02952844, -0.20004147,  0.50679713],
        [-0.17708522, -0.04337656, -0.19148076, -0.6318525 , -0.42213014],
        [-0.00498784, -0.20121223,  0.6661522 ,  0.69222933,  0.84271723]],
       dtype=float32),
 array([[ 0.57098854, -0.42152894, -0.5356864 , -0.33018738,  0.31670478],
        [ 0.0937905 ,  0.28891906, -0.08975235,  0.62407595,  0.7142847 ],
        [ 0.33519432,  0.6845024 ,  0.27502796, -0.5522467 ,  0.19617441],
        [ 0.40629148,  0.42339772, -0.45226407,  0.34050846, -0.5789411 ],
        [-0.6226937 ,  0.30171144, -0.6517681 , -0.28387156,  0.12584937]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [22]:
#Check their shapes
#Should make sense
#First output is input > hidden
#Second output is hidden > hidden
#Third output is bias term (vector of length M)

a, b, c = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [0]:
Wx, Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [24]:
h_last = np.zeros(M) # initial hidden state
x = X[0] # the one and only sample
Yhats = [] # where we store the outputs

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo #We only care about this value on the last iteration
  Yhats.append(y)
  # important: assign h to h_last
  h_last = h

  # print the final output

print(Yhats[-1])


[-0.28235687  0.88105727]


In [0]:
# Bonus exercise: calculate the output for the multiple samples at once (N > 1)